### ISSUE TITLE
Main has been updated but not Use-Case-1-Administration

### ISSUE THREAD

**Issue by Joanes-Iri** [Astrotag/CSCU9P6-Group-Assignment#8]
With the merge of pull request #7 Main branch has been updated but not the branch that we are currently working on.

**Comment by Astrotag** [comment]
Yeah it was my bad, I tried to get the update function working while I was taking a break from decorating and didn't realise I'd pushed to the wrong branch. If people already have started work on the use case then let me know and I will just give you the update code and you can commit it.

**Comment by Astrotag** [comment]
I updated the use case 1 branch with the update mvc code.. Going to close this issue now.
